### ISSUE TITLE
show:file not supported 

### ISSUE THREAD

**Issue by lixiangyu97** [v1nns/spectrum#31]
Hello, after I compile and run this code, when I play music, the output file does not support both mp3 format and wav format. Where is the reason? Is it my package version that is incorrect?

**Comment by v1nns** [comment]
Hi, could you please attach logs from spectrum here?

To execute spectrum with logs enabled, you may use "**-l \<path\>**" as command-line argument (e.g. "**-l /tmp/log.txt**").

**Comment by v1nns** [comment]
I'm closing this issue, if the problem still occurs, please open an issue and attach the full output of spectrum logs.
